#' Convert sinusoidal coordinates to lat / lon
#'
#' @param x sinusoidal x coordinate (vector)
#' @param y sinusoidal y coordinate (vector)
#' @seealso [latlon_to_square()] [square_to_poly()]
#' @keywords MODIS Land Products Subsets, products, meta-data
#' @export
#' @importFrom magrittr %>%
#' @examples
#'
#' \donttest{
#' # Download some test data
#' subset <- mt_subset(product = "MOD11A2",
#'                         lat = 40,
#'                         lon = -110,
#'                         band = "LST_Day_1km",
#'                         start = "2004-01-01",
#'                         end = "2004-03-31")
#'
#' # convert sinusoidal to lat / lon
#' subset <- subset %>%
#'     mutate(result = map2(xllcorner, yllcorner, sin_to_ll)) %>%
#'     unnest()
#'}

sin_to_ll <- function(x, y){
  coords <- sf::st_as_sf(x = data.frame(as.numeric(x),
                                        as.numeric(y),
                                        stringsAsFactors = FALSE),
                     coords = c("as.numeric.x.", "as.numeric.y."),
                     crs = "+proj=sinu +a=6371007.181 +b=6371007.181 +units=m")

  # reproject coordinates
  coords <- sf::st_transform(coords, "+init=epsg:4326")

  # unravel the sf dataframe into a normal one
  coords <- as.data.frame(do.call("rbind", lapply(coords$geometry, unlist)))
  colnames(coords) <- c("longitude_ll", "latitude_ll")

  # return the labelled dataframe
  return(coords)
}

#' Convert lat / lon coordinates to sf bounding box polygon
#'
#' @param lat latitude generated by [sin_to_ll()]
#' @param lon longitude generated by [sin_to_ll()]
#' @param cell_size cell size provided by MODISTools
#' @param nrows cell size provided by MODISTools
#' @param ncols cell size provided by MODISTools
#' @seealso [sin_to_ll()]
#' @keywords MODIS Land Products Subsets, products, meta-data
#' @export
#' @importFrom magrittr %>%
#' @examples
#'
#' \donttest{
#' # Download some test data
#' subset <- mt_subset(product = "MOD11A2",
#'                         lat = 40,
#'                         lon = -110,
#'                         band = "LST_Day_1km",
#'                         start = "2004-01-01",
#'                         end = "2004-03-31")
#'
#' # convert sinusoidal to lat / lon
#' subset <- subset %>%
#'     mutate(result = map2(xllcorner, yllcorner, sin_to_ll)) %>%
#'     unnest()
#'
#'
#'}

ll_to_bb <- function(
  lat,
  lon,
  cell_size,
  nrow,
  ncol
  ){

  # check parameters
  if(missing(res)){
    stop("missing parameter, all parameters are required")
    }

  # meters to a degree
  m_deg = (0.00001/1.1132)

  # transform matrix
  trans <- c(
    0, 0,
    0, 1,
    1, 1,
    1, 0,
    0, 0
  )

  # create coordinate matrix
  m <- c(-cell_size * ncols * m_deg, cell_size * nrows * m_deg) * trans + c(lon, lat)
  m <- matrix(m, 5, 2, byrow = TRUE)

  # convert to a sf polygon
  m %>%
    sf::st_linestring() %>%
    sf::st_cast("POLYGON") %>%
    sf::st_sfc(crs = 4326)
}
