#' Convert sinusoidal coordinates to lat / lon
#'
#' @param x sinusoidal x coordinate (vector)
#' @param y sinusoidal y coordinate (vector)
#' @seealso \code{\link[MODISTools]{ll_to_bb}}
#' @keywords MODIS Land Products Subsets, products, meta-data
#' @export
#' @examples
#'
#' \donttest{
#' # Download some test data
#' subset <- mt_subset(product = "MOD11A2",
#'                         lat = 40,
#'                         lon = -110,
#'                         band = "LST_Day_1km",
#'                         start = "2004-01-01",
#'                         end = "2004-03-31",
#'                         progress = FALSE)
#'
#' # convert sinusoidal to lat / lon
#' lat_lon <- sin_to_ll(subset$xllcorner, subset$yllcorner)
#'
#' # bind with the original dataframe
#' subset <- cbind(subset, lat_lon)
#' head(subset)
#'}

sin_to_ll <- function(x, y){

  # check parameters
  if(missing(x) | missing(y)){
    stop("please provide a coordinate pair in sinusoidal projection...")
  }

  # convert to sf object
  coords <- sf::st_as_sf(x = data.frame(as.numeric(x),
                                        as.numeric(y),
                                        stringsAsFactors = FALSE),
                     coords = c("as.numeric.x.", "as.numeric.y."),
                     crs = "+proj=sinu +a=6371007.181 +b=6371007.181 +units=m")

  # reproject coordinates
  coords <- sf::st_transform(coords, "+init=epsg:4326")

  # unravel the sf dataframe into a normal one
  coords <- as.data.frame(do.call("rbind", lapply(coords$geometry, unlist)))
  colnames(coords) <- c("longitude_ll", "latitude_ll")

  # return the labelled dataframe
  return(coords)
}

#' Convert lat / lon coordinates to sf bounding box polygon
#'
#' @param lat latitude generated by \code{\link[MODISTools]{sin_to_ll}}
#' @param lon longitude generated by \code{\link[MODISTools]{sin_to_ll}}
#' @param cell_size cell size provided by MODISTools
#' @param nrows cell size provided by MODISTools
#' @param ncols cell size provided by MODISTools
#' @seealso \code{\link[MODISTools]{sin_to_ll}}
#' @keywords MODIS Land Products Subsets, products, meta-data
#' @export
#' @examples
#'
#' \donttest{
#' # Download some test data
#' subset <- mt_subset(product = "MOD11A2",
#'                         lat = 40,
#'                         lon = -110,
#'                         band = "LST_Day_1km",
#'                         start = "2004-01-01",
#'                         end = "2004-03-31",
#'                         progress = FALSE)
#'
#' # convert sinusoidal to lat / lon
#' lat_lon <- sin_to_ll(subset$xllcorner, subset$yllcorner)
#'
#' # bind with the original dataframe
#' subset <- cbind(subset, lat_lon)
#'
#' # convert to bounding box
#' bb <- apply(subset, 1, function(x){
#'   ll_to_bb(lon = x['longitude_ll'],
#'            lat = x['latitude_ll'],
#'            cell_size = x['cellsize'],
#'            nrows = x['nrows'],
#'            ncols = x['ncols'])
#' })
#'
#' head(bb)
#'}

ll_to_bb <- function(
  lat,
  lon,
  cell_size,
  nrows,
  ncols
  ){

  # check parameters
  if(missing(cell_size) | missing(lat) | missing(lon) | missing(nrows) |
     missing(ncols)){
    stop("missing parameter, all parameters are required")
  }

  # meters to a degree
  m_deg <- (0.00001/1.1132)

  # transform matrix
  trans <- c(
    0, 0,
    0, 1,
    1, 1,
    1, 0,
    0, 0
  )

  # create coordinate matrix
  m <- c(-as.numeric(cell_size) * as.numeric(ncols) * m_deg,
         as.numeric(cell_size) * as.numeric(nrows) * m_deg) * trans +
    c(as.numeric(lon), as.numeric(lat))
  m <- matrix(m, 5, 2, byrow = TRUE)

  # convert to a sf polygon, with the proper
  # projection etc.
  p <- sf::st_linestring(m)
  p <- sf::st_cast(p, "POLYGON")
  p <- sf::st_sfc(p, crs = 4326)

  # return the polygons
  return(p)
}
